GrabIt/Models/DOWNTIME.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrabIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOWNTIME
    {
        public int DownTimeID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int Area { get; set; }
        public int AffectedArea { get; set; }
        public string Reason { get; set; }
        public string EquipmentTag { get; set; }
        public string ResponsiblePerson { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ShiftTypeID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual GLOBALLOOKUP GLOBALLOOKUP { get; set; }
        public virtual GLOBALLOOKUP GLOBALLOOKUP1 { get; set; }
    }
}

GrabIt/Models/DOWNTIMEVIEW.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrabIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOWNTIMEVIEW
    {
        public int DownTimeID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Area { get; set; }
        public string AffectedArea { get; set; }
        public string Reason { get; set; }
        public string EquipmentTag { get; set; }
        public string ResponsiblePerson { get; set; }
        public string Notes { get; set; }
        public string ShiftType { get; set; }
        public string UserName { get; set; }
    }
}

GrabIt/Controllers/DownTimeController.cs
using GrabIt.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Microsoft.AspNet.Identity;

namespace GrabIt.Controllers
{
    [Authorize]
    public class DownTimeController : Controller
    {
        private GrabItEntities db = new GrabItEntities();
        // GET: DownTime
        public ActionResult Index()
        {
            string userGuid = User.Identity.GetUserId();

            USER usr = db.USERS.Where(item => item.UserNetID == userGuid).SingleOrDefault();
            if (usr == null)
            {
                return RedirectToAction("GetFullName", "Account");
            }
            else
            {

                if (usr.Enabled == null || usr.Enabled == 0)
                {
                    return RedirectToAction("Index", "Home");

                }

                HttpContext.Session["UserName"] = usr.UserName.Trim();
                HttpContext.Session["UserID"] = usr.UserID;
            }

            List<GrabIt.Models.DOWNTIMEVIEW> Model = db.DOWNTIMEVIEWs.OrderByDescending(item => item.Date).Take(100).ToList();
            return View(Model);
        }

        public PartialViewResult DownTimeAdd()
        {
            ViewBag.Area = db.GLOBALLOOKUPs.Where(item => item.LookupCat == 1).ToList();
            ViewBag.AffectedArea = db.GLOBALLOOKUPs.Where(item => item.LookupCat == 2).ToList();
            ViewBag.ShiftType = db.SHIFTTYPES.ToList();

            return PartialView("");
        }

        public JsonResult getEquipmentTag(string text = "")
        {
            if (text.Length < 3) { return this.Json(new List<string>()); }

            return this.Json(db.DOWNTIMEs.Where(item => item.EquipmentTag.Contains(text)).Select(item => item.EquipmentTag).Distinct().Take(10).ToList());
        }

        public JsonResult getReasons(string text = "")
        {
            if (text.Length <= 3) { return this.Json(new List<string>()); }

            return this.Json(db.DOWNTIMEs.Where(item => item.Reason.Contains(text)).Select(item => item.Reason).Distinct().Take(10).ToList());
        }
        public JsonResult getResponsiblePersons(string text = "")
        {
            if (text.Length < 3) { return this.Json(new List<string>()); }

            return this.Json(db.DOWNTIMEs.Where(item => item.ResponsiblePerson.Contains(text)).Select(item => item.ResponsiblePerson).Distinct().Take(10).ToList());
        }

        public int AddDownTime(string date, string startDatetime, string endDatetime, int area, int affectedArea, string reason, string equipmentTag, string responsiblePerson, string notes, int shiftType, bool addOneDay)
        {
            DOWNTIME newDT = new DOWNTIME();

            newDT.Date = DateTime.Parse(date);
            newDT.StartTime = DateTime.Parse(startDatetime);
            newDT.EndTime = DateTime.Parse(endDatetime);
            newDT.Area = area;
            newDT.AffectedArea = affectedArea;
            newDT.Reason = reason;
            newDT.EquipmentTag = equipmentTag;
            newDT.ResponsiblePerson = responsiblePerson;
            newDT.Notes = notes;
            newDT.ShiftTypeID = shiftType;
            newDT.UserID = (int)HttpContext.Session["UserID"];

            if (addOneDay)
            {
                newDT.EndTime = newDT.EndTime.AddDays(1);
            }

            db.DOWNTIMEs.Add(newDT);
            db.SaveChanges();
            return newDT.DownTimeID;
        }

        public int updateDownTime(int DownTimeID, string date, string startDatetime, string endDatetime, int area, int affectedArea, string reason, string equipmentTag, string responsiblePerson, string notes, int shiftType, bool addOneDay)
        {
            DOWNTIME newDT = db.DOWNTIMEs.Where(item => item.DownTimeID == DownTimeID).SingleOrDefault();

            newDT.Date = DateTime.Parse(date);
            newDT.StartTime = DateTime.Parse(startDatetime);
            newDT.EndTime = DateTime.Parse(endDatetime);
            newDT.Area = area;
            newDT.AffectedArea = affectedArea;
            newDT.Reason = reason;
            newDT.EquipmentTag = equipmentTag;
            newDT.ResponsiblePerson = responsiblePerson;
            newDT.Notes = notes;
            newDT.ShiftTypeID = shiftType;

            if (addOneDay)
            {
                newDT.EndTime = newDT.EndTime.AddDays(1);
            }
            db.SaveChanges();
            return newDT.DownTimeID;
        }

        public JsonResult getDownTimeByID(int DownTimeID)
        {
            DOWNTIME newDT = db.DOWNTIMEs.Where(item => item.DownTimeID == DownTimeID).SingleOrDefault();
            var obj = new
            {
                DownTimeID = newDT.DownTimeID,
                Date = newDT.Date.ToString("yyyy-MM-dd"),
                StartTime = newDT.StartTime.ToShortTimeString(),
                EndTime = newDT.EndTime.ToShortTimeString(),
                Area = newDT.Area,
                AffectedArea = newDT.AffectedArea,
                Reason = newDT.Reason.Trim(),
                EquipmentTag = newDT.EquipmentTag.Trim(),
                ResponsiblePerson = newDT.ResponsiblePerson.Trim(),
                Notes = newDT.Notes.Trim(),
                ShiftTypeID = newDT.ShiftTypeID
            };

            return this.Json(obj);
        }
    }
}

GrabIt/Views/DownTime/Index.cshtml
@model IEnumerable<GrabIt.Models.DOWNTIMEVIEW>
@{
    ViewBag.Title = "Downtime";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Downtime</h2>
@MyHelpers.PageLogos()
<script type="text/javascript">
    $(document).ready(function () {
        $('#TblDownTime').dataTable({
            "order": [0, 'desc']
        });
    });
    function scrollto(){
        var Tag = $("#BtnAddDowntime")

        $('html,body').animate({scrollTop: Tag.offset().top}, 'slow');

    }




</script>
<input onclick="scrollto();" type="button" class="btn btn-default" value="Add">
<br />
<table id="TblDownTime" class="table table-striped table-bordered" cellspacing="0" width="100%" style="font-size: 11px;">
    <thead>
        <tr>

            <th style="width:90px;"> Downtime Date</th>
            <th> @Html.DisplayNameFor(model => model.StartTime)</th>
            <th> @Html.DisplayNameFor(model => model.EndTime)</th>
            <th> @Html.DisplayNameFor(model => model.Area)</th>
            <th> @Html.DisplayNameFor(model => model.AffectedArea)</th>
            <th> @Html.DisplayNameFor(model => model.Reason)</th>
            <th> @Html.DisplayNameFor(model => model.EquipmentTag)</th>
            <th> @Html.DisplayNameFor(model => model.ResponsiblePerson)</th>
            <th> @Html.DisplayNameFor(model => model.Notes)</th>
            <th> @Html.DisplayNameFor(model => model.UserName)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            string date = item.Date.ToString("yyyy-MM-dd");
            string start = item.StartTime.ToString("HH:mm");
            string End = item.EndTime.ToString("HH:mm");
            string DowntimeID = item.DownTimeID.ToString();

            <tr>
                <td> @date<span onclick="getDowntimeByID(@DowntimeID)" class="glyphicon glyphicon-pencil" style="color:limegreen; padding-left:20px; cursor: pointer;" title="Edit"></span></td>
                <td> @start</td>
                <td> @End</td>
                <td> @Html.DisplayFor(modelItem => item.Area)</td>
                <td> @Html.DisplayFor(modelItem => item.AffectedArea)</td>
                <td> @Html.DisplayFor(modelItem => item.Reason)</td>
                <td> @Html.DisplayFor(modelItem => item.EquipmentTag)</td>
                <td> @Html.DisplayFor(modelItem => item.ResponsiblePerson)</td>
                <td> @Html.DisplayFor(modelItem => item.Notes)</td>
                <td> @Html.DisplayFor(modelItem => item.UserName)</td>

            </tr>
        }
    </tbody>
</table>
<div class="horizontalRule"></div>
@{Html.RenderAction("DownTimeAdd", "DownTime");}