GrabIt/Controllers/DataInputController.cs
using GrabIt.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace GrabIt.Controllers
{
    [Authorize]
    public class DataInputController : Controller
    {
        // GET: DataInput
        private GrabItEntities db = new GrabItEntities();
        public ActionResult Index()
        {
            //Here we check if the user has a unser name and also has been Enabled to View this Page
            string userGuid = User.Identity.GetUserId();
            USER usr = db.USERS.Where(item => item.UserNetID == userGuid).SingleOrDefault();
            if (usr == null)
            {
                return RedirectToAction("GetFullName", "Account");
            }
            else
            {

                if (usr.Enabled == null || usr.Enabled == 0)
                {
                    return RedirectToAction("Index", "Home");

                }

                HttpContext.Session["UserName"] = usr.UserName.Trim();
                HttpContext.Session["UserID"] = usr.UserID;
            }

            return View();
        }
        //Return a singe process by ProcessID
        public JsonResult GetProcessByProcessID(int ProcessID)
        {

            var items = (from u in db.PROCESSES
                 join e in db.PROCESSTYPES on u.ProcessTypeID equals e.ProcessTypeID
                 where u.ProcessID == ProcessID

                  select new
            {
                ShiftTypeID = u.ShiftTypeID,
                Date = u.Date.ToString(),
                StartTime = u.StartTime,
                EndTime = u.EndTime,
                ProcessTypeID = u.ProcessTypeID,
                UserID = u.UserID,
                Completed = u.Completed,
                ProcessCategoryID = e.ProcessCategoryID
            }).SingleOrDefault();

            return Json(items, JsonRequestBehavior.AllowGet);

        }

        public PartialViewResult ProcessAddView()
        {
            return PartialView("ProcessAddView");
        }

        public PartialViewResult ProcessAddedlist(string date = "")
        {
            DateTime theDate;
            if (date == "")
            {
                theDate = DateTime.Now.Date;

            }
            else
            {
                theDate = DateTime.Parse(date);
            }

            var model = db.ProcessesViews.Where(item => item.Date == theDate).ToList();

            return PartialView(model);
        }

        public PartialViewResult GetShiftType()
        {
            var model = db.SHIFTTYPES.ToList();
            return PartialView(model);
        }

        public PartialViewResult GetProcessType(int catID)
        {
            var model = db.PROCESSTYPES.Where(Item => Item.ProcessCategoryID == catID).ToList();
            return PartialView(model);
        }

        public PartialViewResult GetProcessCat()
        {
            var model = db.PROCESSCATEGORIES.ToList();
            return PartialView(model);
        }

        //measurements
        public PartialViewResult GetMeasurements(int ProcessTypeID)
        {
            Measurements modelItem = new Measurements();

            modelItem.SortByCat(db.MEASUREMENTVIEWs.Where(item => item.ProcessTypeID == ProcessTypeID).ToList());
            var model = modelItem.MeasurementsByCat;

            return PartialView(model);
        }

        public JsonResult GetMeasurementsList(int ProcessTypeID)
        {

            List<MEASUREMENTVIEW> items = db.MEASUREMENTVIEWs.Where(item => item.ProcessTypeID == ProcessTypeID).ToList();
            foreach (MEASUREMENTVIEW mes in items)
            {
                mes.Desc = mes.Desc.Trim();
            }

            return Json(items, JsonRequestBehavior.AllowGet);

        }

        public JsonResult GetMeasurementsByProcessID(int ProcessID)
        {

            var items = db.MEASUREMENTS.Where(item => item.ProcessID == ProcessID).Select(u => new { ID = u.MeasurementTypeID, Value = u.Value });
            return Json(items, JsonRequestBehavior.AllowGet);

        }

        public int checkProcessExist(PROCESS prs)
        {

            PROCESS current = db.PROCESSES.SingleOrDefault(item => item.ShiftTypeID == prs.ShiftTypeID && item.Date == prs.Date && item.ProcessTypeID == prs.ProcessTypeID);
            if (current != null)
            {
                return current.ProcessID;
            }else{
                return 0;
            }

        }
        public int AddProcess(PROCESS prs)
        {

            PROCESS current = db.PROCESSES.SingleOrDefault(item => item.ShiftTypeID == prs.ShiftTypeID && item.Date == prs.Date && item.ProcessTypeID == prs.ProcessTypeID);
            if (current != null)
            {
                current.ShiftTypeID = prs.ShiftTypeID;
                current.Date = prs.Date;
                current.StartTime = prs.StartTime;
                current.EndTime = prs.EndTime;
                current.ProcessTypeID = prs.ProcessTypeID;
                current.UserID = (int)HttpContext.Session["UserID"];
                current.Completed = prs.Completed;
               
            }
            else
            {
                prs.UserID = (int)HttpContext.Session["UserID"];
                db.PROCESSES.Add(prs);
            }

           
            db.SaveChanges();
            return prs.ProcessID;
        }

        public int AddMeasurement(MEASUREMENT Measure)
        {
            MEASUREMENT DBMeasure = db.MEASUREMENTS.SingleOrDefault(item => item.MeasurementTypeID == Measure.MeasurementTypeID && item.ProcessID == Measure.ProcessID);
            if (DBMeasure != null)
            {
                DBMeasure.Value = Measure.Value;
                db.SaveChanges();
            }
            else
            {
                db.MEASUREMENTS.Add(Measure);
            }
            db.SaveChanges();

            int pt = db.PROCESSES.Where(item => item.ProcessID == Measure.ProcessID).Select(row => row.ProcessTypeID).SingleOrDefault();
            int count = db.MEASUREMENTLINKs.Where(item => item.ProcessTypeID == pt).Count();
            int mesCount = db.MEASUREMENTS.Where(item => item.ProcessID == Measure.ProcessID).Count();
            if (count == mesCount)
            {
                PROCESS pros = db.PROCESSES.SingleOrDefault(item => item.ProcessID == Measure.ProcessID);
                pros.Completed = true;
                db.SaveChanges();
            }

            return Measure.ProcessID;
        }
    }

    public class Measurements
    {
        public List<List<MEASUREMENTVIEW>> MeasurementsByCat = new List<List<MEASUREMENTVIEW>>();

        public void SortByCat(List<MEASUREMENTVIEW> Measures)
        {

            Dictionary<string, int> catsdone = new Dictionary<string, int>();
            int CatCnt = 0;
            foreach (MEASUREMENTVIEW item in Measures)
            {
                item.Desc = item.Desc.Trim();
                if (catsdone.Keys.Contains(item.Category))
                {
                    MeasurementsByCat[catsdone[item.Category]].Add(item);
                }
                else
                {
                    catsdone.Add(item.Category, CatCnt++);

                    MeasurementsByCat.Add(new List<MEASUREMENTVIEW>());

                    MeasurementsByCat[catsdone[item.Category]].Add(item);

                }
            }
        }
    }
}

GrabIt/Views/DataInput/GetMeasurements.cshtml
@model List<List<GrabIt.Models.MEASUREMENTVIEW>>
@{
    ViewBag.Title = "GetMeasurements";
}

<h3>Measurements</h3>
<script type="text/javascript">
    $(document).ready(function () {
        $(".measurementval").keyup(function () {
            console.log(".measurementval");
            CheckFormMeasurementscomplete();
        })

    });

    function CheckFormMeasurementscomplete() {
        var count = MeasurementsList.length;
        var counted = 0;
        $.each(MeasurementsList, function (index, item) {
            var val = $("#" + item.MeasurementTypeID).val();
            if (val != "") {
                counted++;
            }
        });
        if (count == counted) {
            $("#BtnSaveMeasurements").val("Complete");
        }
    }

</script>
@foreach (var Cat in Model)
{
    <h4><b>@Html.DisplayFor(cat => Cat[0].Category)</b></h4>
    <div class="container" style="margin-top:15px;margin-left:15px;">
        <div class="row">
            @foreach (var Measurement in Cat)
            {
                var range = "";
                if (Measurement.LowerLimit != null && Measurement.UpperLimit != null)
                {
                    range = Measurement.LowerLimit.ToString() + " < " + Measurement.Desc + " < " + Measurement.UpperLimit.ToString();
                }
                else if (Measurement.LowerLimit == null && Measurement.UpperLimit != null)
                {
                    range = Measurement.Desc + " < " + Measurement.UpperLimit.ToString();
                }
                else if (Measurement.LowerLimit != null && Measurement.UpperLimit == null)
                {
                    range = Measurement.LowerLimit.ToString() + " < " + Measurement.Desc;
                }
                else
                {
                    range = "-";
                }
                <div class="form-group col-sx-5 col-sm-4 col-md-3">
                    <label class="col-sx-2 control-label" for="Name">@Html.DisplayFor(msr => Measurement.Desc):</label>
                    <div class="col-sx-10">
                        <input id="@Html.DisplayFor(msr => Measurement.MeasurementTypeID)" type="number" class="form-control measurementval">
                    </div>
                    <label class="col-sx-2 control-label" style="color: red;"><small>@range</small></label>
                </div>

            }
        </div>
    </div>
    <div class="horizontalRule"></div>
}

GrabIt/Views/DataInput/GetProcessCat.cshtml
@model IEnumerable<GrabIt.Models.PROCESSCATEGORy>


<script type="text/javascript">
    $(document).ready(function () {
        $("#SelCatType").change(function () {
            $("#DivProcessType").slideUp('slow');
            $.ajax({
                url: '@(Url.Action("GetProcessType", "DataInput"))',
                data: { catID: $("#SelCatType").val() },
                success: function (data) {
                    $("#DivProcessType").html(data).slideDown('slow');
                    if (selectedProcess) {

                        $("#SelProcessType").val(selectedProcess.ProcessTypeID);

                        $("#SelProcessType").attr("disabled", true);
                    }
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Failed to retrieve books.');
                }
            });
        });
    });



</script>

<div id="divCatType" class="form-group">
    <label class="col-sx-2 control-label" for="SelCatType">Process Category: </label>
    <div class="col-sx-10">
        <select id="SelCatType" class="form-control" onchange="validateCatType();">
            <option value="">Please Select</option>
            @foreach (var item in Model)
            {
                <option value="@Html.DisplayFor(modelItem => item.ProcessCategoryID)">@Html.DisplayFor(modelItem => item.Desc)</option>
            }
        </select>
    </div>
</div>

GrabIt/Views/DataInput/GetProcessType.cshtml
@model IEnumerable<GrabIt.Models.PROCESSTYPE>

<div id="divProcessType" class="form-group">
    <label class="col-sx-2 control-label" for="SelProcessType">Process Type:</label>
    <div class="col-sx-10">
        <select id="SelProcessType" class="form-control" onchange=" validateProcessType();">
            <option value="">Please Select</option>
            @foreach (var item in Model)
            {
                <option value="@Html.DisplayFor(modelItem => item.ProcessTypeID)">@Html.DisplayFor(modelItem => item.Desc)</option>
            }
        </select>
    </div>
</div>

GrabIt/Views/DataInput/GetShiftType.cshtml
@model IEnumerable<GrabIt.Models.SHIFTTYPE>

<div id="divShiftType" class="form-group">
    <label class="col-sx-2 control-label" for="SelShiftType">Shift Type:</label>
    <div class="col-sx-10">
        <select id="SelShiftType" class="form-control" onchange="validateShiftType();">
            <option value="">Please Select</option>
            @foreach (var item in Model)
            {
                <option value="@Html.DisplayFor(modelItem => item.ShiftTypeID)">@Html.DisplayFor(modelItem => item.Desc)</option>
            }
        </select>
    </div>
</div>

GrabIt/Views/DataInput/Index.cshtml
@{
    ViewBag.Title = "DataInput";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<script type="text/javascript">
    $(document).ready(function () {
        $("#datepicker").datepicker({ dateFormat: 'yy-mm-dd' });
        var myDate = new Date();
        var day = myDate.getDate();

        day = day < 10 ? "0" + day : day;


        var prettyDate = myDate.getFullYear() + '-' + (myDate.getMonth() + 1) + '-' + day;
        $("#datepicker").val(prettyDate);

        $("#BtnAddShift").click(function () {
            $("#ProcessBlockContainer").slideUp('slow');

            selectedProcess = null
            $("#SelShiftType").attr("disabled", false);
            $("#SelProcessType").attr("disabled", false);
            $.ajax({
                url: '@(Url.Action("ProcessAddView", "DataInput"))',
                data: {},
                success: function (data) {
                    $("#ProcessBlock").html(data)
                    $("#ProcessBlockContainer").slideDown('slow');
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    console.log(thrownError);
                }
            });
        });


    });
    function dateChanged() {
        console.log($("#datepicker").val());
        $("#ProcessesView").slideUp('slow');
        $.ajax({
            url: '@(Url.Action("ProcessAddedlist", "DataInput"))',
            data: { date: $("#datepicker").val() },
            success: function (data) {
                $("#ProcessesView").html(data).slideDown('slow');
            },
            error: function (xhr, ajaxOptions, thrownError) {
                console.log(thrownError);
            }
        });

    }
    function getMeasurements(ProcessID, ProcessTypeID) {
        var done = $.Deferred();
       
        console.log("getMeasurements(" + ProcessID + ")");
        $.ajax({
            url: '@(Url.Action("GetMeasurements", "DataInput"))',
            data: { ProcessTypeID: ProcessTypeID },
            success: function (data) {
                $("#MeasurementsBlock").html(data).slideDown('slow');
                $("#divBtnSave").slideDown("slow");
                done.resolve(true);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                console.log(thrownError);
                done.resolve(false);
            }
        });
        return done;
    }
    function getMeasurementsList(ProcessTypeID) {
        var doneMesList = $.Deferred();
        $.ajax({
            url: '@(Url.Action("GetMeasurementsList", "DataInput"))',
            data: { ProcessTypeID: ProcessTypeID },
            contentType: 'application/json',
            success: function (data) {
                MeasurementsList = [];
                $.each(data, function (index, item) {
                    item.Desc = $.trim(item.Desc);
                    MeasurementsList.push(item);
                });
                doneMesList.resolve(true);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                console.log(thrownError);
                doneMesList.resolve(false);
            }
        });
        return doneMesList;

    }
    function getMeasurementsByProcessID(ProcessID) {

        $.ajax({
            url: '@(Url.Action("GetMeasurementsByProcessID", "DataInput"))',
            data: { ProcessID: ProcessID },
            contentType: 'application/json',
            success: function (data) {
                $.each(data, function (index, item) {
                    $("#" + item.ID).val($.trim(item.Value));
                });
                console.log(data);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                console.log(thrownError);
            }
        });
    }
    var deflist;
    function saveMeasurements() {
        if (currentProcessID == 0) {
            return false;
        }
        var allDone = true;
        MeasurementCount = 0;
        deflist = [];

        $.each(MeasurementsList, function (index, item) {
            var val = $("#" + item.MeasurementTypeID).val();
            MeasurementCount++;
            deflist.push(new $.Deferred());
            if (val != "") {
               
                var obj = {
                    ProcessID: currentProcessID,
                    MeasurementTypeID: item.MeasurementTypeID,
                    Value: val
                }
                
                console.log("Start: " + MeasurementCount)
                saveMeasurement(obj, MeasurementCount-1);
            } else {
                deflist[MeasurementCount - 1].resolve(true);
                allDone = false;
            }
        });
        console.log("When")
        $.when.apply($, deflist).done(function () {
            console.log("When done")
            $("#ProcessBlockContainer").hide("slow");
            $("#MeasurementsBlock").hide("slow");
            dateChanged();
            $("#BtnAddShift").attr("disabled", false);
          
        });
    }

    function saveMeasurement(MeasurmentObject, indx) {
        $.ajax({
            url: '@(Url.Action("AddMeasurement", "DataInput"))',
            data: MeasurmentObject,
            success: function (data) {
                console.log("End: " + indx);
                deflist[indx].resolve(true);
            },
            error: function (xhr, ajaxOptions, thrownError) {

            }
        });
    }

    function getProcessByProcessID(ProcessID) {
        currentProcessID = ProcessID;
        $.ajax({
            url: '@(Url.Action("GetProcessByProcessID", "DataInput"))',
            data: { ProcessID: ProcessID },
            contentType: 'application/json',
            success: function (data) {
                if (data) {
                    selectedProcess = data;
                    $("#BtnAddShift").attr("disabled", true);
                    $("#ProcessBlockContainer").slideUp();
                    $.ajax({
                        url: '@(Url.Action("ProcessAddView", "DataInput"))',
                        data: {},
                        success: function (data) {
                            $("#ProcessBlock").html(data);
                            //Set the Data
                            $("#SelShiftType").val(selectedProcess.ShiftTypeID);
                            $("#SelCatType").val(selectedProcess.ProcessCategoryID);
                            //this is here to update the ProcessType select Box
                            $("#SelCatType").change();
                            $("#TxtStartTime").val($.trim(selectedProcess.StartTime));
                            $("#TxtEndTime").val($.trim(selectedProcess.EndTime));
                            $("#SelShiftType").attr("disabled", true);
                            $("#SelCatType").attr("disabled", true);
                          
                            $("#ProcessBlockContainer").slideDown("slow");
                            $.when(
                             getMeasurements(ProcessID, selectedProcess.ProcessTypeID),
                             getMeasurementsList(selectedProcess.ProcessTypeID)).done(function () {
                                 getMeasurementsByProcessID(ProcessID);
                             });
                            $("#BtnAddProcess").val("Save");
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            console.log(thrownError);
                        }
                    });
                }
            },
            error: function (xhr, ajaxOptions, thrownError) {
                console.log(thrownError);
            }
        });
    }
    var MeasurementsList = [];
    var MeasurementCount = 0;
    var selectedProcess = null;
    var currentProcessID = 0;

</script>

<h2>Lab Results</h2>
@MyHelpers.PageLogos()
<h4>Here you can capture the shift info</h4>
<div style="margin-left:15px;">
    <div class="form-group">
        <label class="col-sx-2 control-label" for="TxtEndTime">Date:</label>
        <div class="col-sx-10">
            <input id="datepicker" type="text" class="form-control" onchange="dateChanged();" />
        </div>
    </div>
    <div id="ProcessesView">
        @{Html.RenderAction("ProcessAddedlist", "DataInput");}
    </div>
    <input id="BtnAddShift" type="button" class="btn btn-default" value="Add Shift" />
    <div class="horizontalRule"></div>
</div>
<div id="ProcessBlockContainer">
    <div id="ProcessBlock"></div>
    <div id="MeasurementsBlock"></div>
  
    <div id="divBtnSave" style="display: none;">
        <input id="BtnSaveMeasurements" type="button" class="btn btn-default" value="Save" onclick="saveMeasurements();" />
    </div>
</div>

GrabIt/Views/DataInput/ProcessAddView.cshtml
<h4>Please enter the process details.</h4>
<script type="text/javascript">
    function validateAndSaveProcess() {

        if (!validateAddProcess()) return false;

        var ProcObj = {

            ShiftTypeID: $("#SelShiftType").val(),
            Date: $("#datepicker").val(),
            StartTime: $("#TxtStartTime").val(),
            EndTime: $("#TxtEndTime").val(),
            ProcessTypeID: $("#SelProcessType").val(),
            UserID: 1,
            Completed: false,
            ProcessID: selectedProcess
        }


        $.ajax({
            url: '@(Url.Action("checkProcessExist", "DataInput"))',
            data: ProcObj,
            success: function (CheckedID) {
                if (CheckedID == 0 || $("#BtnAddProcess").val() == "Save") {
                    $.ajax({
                        url: '@(Url.Action("AddProcess", "DataInput"))',
                        data: ProcObj,
                        success: function (data) {
                            if (CheckedID == 0) getMeasurements(data, $("#SelProcessType").val());
                            selectedProcess = data;
                            dateChanged();

                            $("#SelShiftType").attr("disabled", true);
                            $("#SelCatType").attr("disabled", true);
                            $("#SelProcessType").attr("disabled", true);

                            $("#BtnAddProcess").val("Save");
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            console.log(thrownError);
                        }
                    });
                } else {
                    BootstrapDialog.show({
                        message: 'The Shift has been captured, do you want to edit it?',
                        buttons: [{
                            label: 'Cancel',
                            action: function (dialogRef) {
                                dateChanged();
                                $("#ProcessBlock").hide("slow");
                                $("#MeasurementsBlock").hide("slow");
                                dateChanged();
                                $("#BtnAddShift").attr("disabled", false);
                                dialogRef.close();
                            }
                        }, {
                            label: 'OK',
                            cssClass: 'btn-primary',
                            action: function (dialogRef) {
                                getProcessByProcessID(CheckedID);
                                dialogRef.close();
                            }
                        }],
                        type: BootstrapDialog.TYPE_WARNING,
                        closable: false,
                    });
                }
            },
            error: function (xhr, ajaxOptions, thrownError) {
                console.log(thrownError);
            }
        });

    }
    function validateStartTime() {
        var val = $("#TxtStartTime").val();
        if (val == "") {
            $("#divStartTime").addClass("has-error");
            return false;
        } else {
            $("#divStartTime").removeClass("has-error");
            return true;
        }

    }
    function validateEndTime() {
        var val = $("#TxtEndTime").val();
        if (val == "") {
            $("#divEndTime").addClass("has-error");
            return false;
        } else {
            $("#divEndTime").removeClass("has-error");
            return true;
        }

    }
    function validateShiftType() {
        var val = $("#SelShiftType").val();
        if (val == "") {
            $("#divShiftType").addClass("has-error");
            return false;
        } else {
            $("#divShiftType").removeClass("has-error");
            return true;
        }

    }
    function validateCatType() {
        var val = $("#SelCatType").val();
        if (val == "") {
            $("#divCatType").addClass("has-error");
            return false;
        } else {
            $("#divCatType").removeClass("has-error");
            return true;
        }

    }
    function validateProcessType() {
        var val = $("#SelProcessType").val();
        if (val == "") {
            $("#divProcessType").addClass("has-error");
            return false;
        } else {
            $("#divProcessType").removeClass("has-error");
            return true;
        }

    }
    function validateAddProcess() {
        return validateStartTime() & validateEndTime() & validateShiftType() & validateCatType() & validateProcessType();
    }

</script>

<form id="addProcessForm" class="form-horizontal" data-bv-feedbackicons-valid="glyphicon glyphicon-ok" data-bv-feedbackicons-invalid="glyphicon glyphicon-remove" data-bv-feedbackicons-validating="glyphicon glyphicon-refresh">

    <div class="container" style="margin-top:15px;margin-left:15px;">
        <div class="row">
            <div class="col-xs-5">
                @{Html.RenderAction("GetShiftType", "DataInput");}

                <div id="divStartTime" class="form-group col-md-6" style="margin-left: -60px;">
                    <div class="col-xs-12">
                        <label class="col-xs-8 control-label" for="TxtStartTime">Start Time:</label>
                        <div class="col-xs-10">
                            <input id="TxtStartTime" type="time" class="form-control" name="TxtStartTime" onchange="validateStartTime();">
                        </div>
                    </div>
                </div>

                <div id="divEndTime" class="form-group col-md-6" style="margin-left: -45px;">
                    <div class="col-xs-12">
                        <label class="col-xs-8 control-label" for="TxtEndTime">End Time:</label>
                        <div class="col-xs-10">
                            <input id="TxtEndTime" type="time" class="form-control" onchange="validateEndTime();">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-5">
                <div class="form-group col-md-10">
                    @{Html.RenderAction("GetProcessCat", "DataInput");}
                    <div id="DivProcessType"></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <input id="BtnAddProcess" type="button" class="btn btn-default" style="margin-left: 15px;margin-top: 20px;" value="Add" onclick="validateAndSaveProcess();" />
                <div class="horizontalRule"></div>
            </div>
        </div>
        <div style="clear:both"></div>
    </div>
</form>

GrabIt/Views/DataInput/ProcessAddedlist.cshtml
@model IEnumerable<GrabIt.Models.ProcessesView>
<script type="text/javascript">
    $(document).ready(function () {
        $('#ProcessList').dataTable();
    });
</script>
<br />
<table id="ProcessList" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
           
            <th> @Html.DisplayNameFor(model => model.Date)</th>
            <th> @Html.DisplayNameFor(model => model.Shift)</th>
            <th> @Html.DisplayNameFor(model => model.StartTime)</th>
            <th> @Html.DisplayNameFor(model => model.EndTime)</th>
            <th> @Html.DisplayNameFor(model => model.Desc)</th>
            <th> @Html.DisplayNameFor(model => model.UserName)</th>
            <th> Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            string date = item.Date.ToString("yyyy-MM-dd");
            <tr>
                
                <td> @date<span onclick="getProcessByProcessID(@Html.DisplayFor(modelItem => item.ProcessID)); " class="glyphicon glyphicon-pencil" style="color:limegreen; padding-left:20px; cursor: pointer;" title="Edit"></span></td>
                <td> @Html.DisplayFor(modelItem => item.Shift)</td>
                <td> @Html.DisplayFor(modelItem => item.StartTime)</td>
                <td> @Html.DisplayFor(modelItem => item.EndTime)</td>
                <td> @Html.DisplayFor(modelItem => item.Desc)</td>
                <td> @Html.DisplayFor(modelItem => item.UserName)</td>
                @if (item.Completed)
                {

                    <td><span class="glyphicon glyphicon-ok-circle" style="color:limegreen;display:block; text-align:center; margin:0 auto;" title="Complete"></span></td>
                }
                else
                {
                    <td><span class="glyphicon glyphicon-remove-circle" style="color:red;display:block; text-align:center; margin:0 auto;" title="Incomplete"></span></td>
                }

            </tr>
        }
    </tbody>
</table>